# Loads default set of integrations. Do not remove.
default_config:

light:
  - platform: oelo_lights
    ip_address: "192.168.32.39"
    # name: "Oelo Lights"
    # zone: 1,

  # - platform: "example_light"
  #   host: "stuff"

sensor:
  - platform: github_custom
    access_token: !secret github_access_token
    repositories:
      - path: "home-assistant/core"
        name: "Home Assistant Core"
      - path: "boralyl/steam-wishlist"

  - platform: github_custom
    url: https://my.enterprisegithubserver.com
    access_token: !secret github_access_token
    repositories:
      - path: "company/some-repo"

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
