name: Validate with hassfest and HACS

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS Action
        uses: hacs/action@22.5.0
        with:
          category: integration
